---
matrix:
  include:
     - language: go
       depth: 1

       version: 1.1.x

       email: false

     - language: node_js
       cache:
         directories:
           - node_modules

       addons:
         chrome: stable

       before_install:
         - cd web

       install:
         - npm install

       deploy:
         provider: "firebase"
         token:
           secure: "elea3JWCXuwo/mMb9YLM5qR4ZOK+tvX3DkaRcBZ2Q5x6KoWKJCfWlKcAuZLR+z67nCw9cFHgL8SvuRRIngUcchE+dGM84x0Wm+KbwEb2NELOQcQq5tZCJYkIVmQug6FcTs8VPT0Dq0NmX2tTVPsvxoy6846XED2B51U23bp00b4GYz850Mwrpnf7uq+VkXSI2Zhg9lNizJnufEdgQRdpNo3gkLxouQnidshnqmCG89srEg62VNhtjUbKLity7C8zrwCrDofEBjDYB/g0+Zl3hGm92TMU7YNRCXTn5ju2JsfmHggUjHEgirR2vWTzT2Yh/QQuEhHefGBQCTByjxwt7qHMsyNIG/fsV09v9BDIXXK+dg2Ffk2Uxi1jqeNV4QNiWEE3yu8nW7pY6f5qvwbKm9TaFfe7W31UlWSWZ6xewzAPb1l+S/J+elch/sbNM+mOqcYI+KgVFV53COD4Ep3sDNkLootSV8kiXVd8gXH4BzI8h4BS05ii14J+V6WqbG5DHNlvrMDVPEHTruobLDkLq5KQ82SW0F0ukd/MdXEaao5Dy9RVes63x3D75hJ4fXlZIR4e3O8a+gMhiGGPkV7l9zLPASB1WAr2BYQP+t9pZPSmbegwti900oyaFzNdUxSwes37rVrhK4v7ElfKWCSi1Rz/X0B481F6J9XCHRE="
         message: "Deploying to firebase..."

# notifications:
#   email: false
#   on_success: never
#   on_failure: always
#   slack:
#     secure: gDemyn8zvjkPvpf7fr9PHl5zhc4aD4tiLrsFhe7XvRKB8w2Bkd21SbP09kmzY8brti2s9gLt+2pZaqcj8rdqk+GbpEAQzqQWNL2Pd819mMTu91zSAvSFuFH8FCbrKRvka1JfVj7eyHn8FlbdHBQkViuPmuCfJC3DY59/3rL/KO3tcUJMBRuktc7jUWLrH4Y1WQ1WZoW+anrG1pH8jne5QkT5yDMrmicoWCU3XeIFKCKtb6H7AnVQt/B6N6Ypil88cHAgj9RHifZZHFS4N2N+q2DobrAO+NP8mUPabwqICGBD+2L9z7nXCqzA24xfde600hqbZGlwEcxad/W9E3ftw/cQIejiLNqtA+vrR+3cFGLOK4W79dCYolBESV+7V1tkB6faES8LQU/Qe3yeNJKGvmgwwBRhWLiNgCZnPlk3ZtWezyOTYMSz85aMGatVeKrmxkO2tgNK2/wfn3/jKSKa6g/GsL6AFOWX+NXnh3XbDLmbPADJ2Waf8jqgzpd9EBs9FJBJxBpYSvOrUE52jnCzIsWhr9Lmgp1e8HJAuJEl9GpEnASXEtAjEgwf0mLJ8K1AsRTGHPTx0KF2phcrWvozg078DtEjvTjQmKQw03BqpoQAAWBfzpOA88V6i8E3QN2oYZNh9HMGrT3enhptNmkXiia8EQfuLo6mE+NGJ+8nCqY=
